android:
  config:
    "dynatrace {
      configurations {
        defaultConfig {
          autoStart{
            applicationId '690d765d-38e2-4bdf-bc05-a6dd19f0b64d'
            beaconUrl 'https://bf28127fnf.bf.dynatrace.com/mbeacon'
          }
          userOptIn false
          agentBehavior.startupLoadBalancing true
        }
      }
    }"

ios:
  config:
    "<key>DTXApplicationID</key>
    <string>690d765d-38e2-4bdf-bc05-a6dd19f0b64d</string>
    <key>DTXBeaconURL</key>
    <string>https://bf28127fnf.bf.dynatrace.com/mbeacon</string>
    <key>DTXUserOptIn</key>
    <false/>
    <key>DTXStartupLoadBalancing</key>
    <true/>"